- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable backend service
  # tags:
  # - deployment
  ansible.builtin.service:
    name: backend
    state: started
    enabled: yes